version: "3"

tasks:
  doc:
    desc: Watch and serve documentation (requires node)
    cmds:
      - cargo doc
      - npx live-server target/doc &
      - cargo watch -s "cargo doc --target-dir target/doc_live && cp -R target/doc_live/doc/* target/doc"
  #   deps:
  #     - _doc:watch
  #     - _doc:serve
  #
  # _doc:watch:
  #   cmds:
  #     - cargo watch -x doc
  #
  # _doc:serve:
  #   cmds:
  #     - npx live-server target/doc
