version: "3"

tasks:
  doc:
    desc: Watch and serve documentation
    cmds:
      - txtpp src -r && cargo doc
      - live-server target/doc -p 8080 &
      - cargo watch -s "txtpp src -r -N && cargo doc"

  dev:
    desc: Dev inner loop. Run tests in watch mode
    cmds:
      - cargo watch -s "cargo test {{.CLI_ARGS}}"

  refresh:
    desc: Refresh macro tests
    env:
      MACROTEST: overwrite
    cmds:
      - cargo test --test macrotest
