version: "3"

tasks:
  book:
    desc: Watch and serve the book
    cmds:
      - txtpp book -r
      - mdbook serve book -n 0.0.0.0 &
      - cargo watch -s "txtpp book -r -N"

  doc:
    desc: Watch and serve documentation
    cmds:
      - txtpp src -r && cargo doc
      - live-server target/doc -p 8080 &
      - cargo watch -s "txtpp src -r -N && cargo doc"

  dev:
    desc: Dev inner loop. Run tests in watch mode
    cmds:
      - cargo watch -s "cargo test {{.CLI_ARGS}}"

  refresh:
    desc: Refresh test snapshots
    env:
      MACROTEST: overwrite
    cmds:
      - cargo test --test macrotest
